### PR TITLE
Create ruby.md

### PR DESCRIPTION
**Pull request by ghost**
Ruby gem for nekos-best

- [X] My pull request follows the [Contributing Guidelines](https://github.com/nekos-best/docs#contributing-guidelines).

- [X] My submission is well documented.
- [X] My submission is ordered alphabetically.
- [X] My submission is listed under "src/examples/unofficial/"
- [X] My submission is not a duplicate of an already existing example.

### CODE REVIEW

**Comment by Thusuzzee** [comment]
Please read the [Contributing](https://github.com/nekos-best/docs#contributing) part again. 

Also don't remove the "Pull Request check", it's there for a reason.

**Comment by oriel-beck** [comment]
The package is inconsistent, requesting under 1 defaults to 1 but requesting above 20 throws an error, please be consistent.
It also seems to accept strings and numbers as the second option.
Please fix the above issues and notify me, I will review your package again.

**Comment by oriel-beck** [comment]
Noticed another issue, your package returns strings instead of raising exceptions when something is incorrect, this will cause issues with complex programs.
I advise you raise an exception instead of returning strings.

**Comment by Thusuzzee** [comment]
I'm going to close this PR. The reason is pretty simple, we are not satisfied with the code's quality of your package.
Feel free to open a new PR again after you improved your package's code quality.

**Pull request closed without merging**
